### ISSUE TITLE
README is out of date

### ISSUE THREAD

**Issue by sand7000** [Open-MBEE/mms5-layer1-openapi#2]
README says to use the generated yaml/json OpenAPI documents in the branch "build/docs". Those files result in spec validation errors when generating code with openapi-generator-cli and (if you ignore that) result in incorrectly generated api. I generated java jars and found several things were missing and or wrong compared to the docs.

I regenerated the yaml/json from the main branch of the repo and the results are (so far) better. No validation errors,  no missing classes and the generated API seems to match the docs.

I suggest updating the README to either point to a new correct OpenAPI document or to just say to generate the doc manually.

Thanks!

**Comment by sand7000** [comment]
Hmm I seem to have spoken too soon. I don't get validation errors but there are still things missing in the generated jars. So far I am seeing:

```
Caused by: java.lang.ClassNotFoundException: org.openapitools.client.Configuration cannot be found
```

and 

```
Caused by: java.lang.ClassNotFoundException: org.openapitools.client.ApiException cannot be found
```

**Comment by sand7000** [comment]
To verify I am not doing something wrong in my eclipse setup I recreated the example from the generated docs:

```
// Import classes:
import org.openapitools.client.ApiClient;
import org.openapitools.client.Configuration;
import org.openapitools.client.auth.*;
import org.openapitools.client.model.*;
import org.openapitools.client.api.StructuralReadsApi;

public class Example {
  public static void main(String[] args) {
    ApiClient defaultClient = Configuration.getDefaultApiClient();
    defaultClient.setBasePath("http://localhost");
    
    // Configure HTTP bearer authorization: bearerAuth
    HttpBearerAuth bearerAuth = (HttpBearerAuth) defaultClient.getAuthentication("bearerAuth");
    bearerAuth.setBearerToken("BEARER TOKEN");

    StructuralReadsApi apiInstance = new StructuralReadsApi(defaultClient);
    try {
      String result = apiInstance.readAllOrgs();
      System.out.println(result);
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
}
```

and compiled and ran it by hand:

```
$ javac -cp ".:/home/sand7000/projects/indigo/mmsopenapi/target/openapi-java-client-1.0.0.jar" Example.java
$ java Example
Exception in thread "main" java.lang.NoClassDefFoundError: org/openapitools/client/Configuration
	at Example.main(Example.java:10)
Caused by: java.lang.ClassNotFoundException: org.openapitools.client.Configuration
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
```

**Comment by sand7000** [comment]
This is looking like user error. I think I have it sorted out. Closing ticket.
